sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage

after_success:
  - docker build -t react-client ./client
  - docker build -t nginx-router ./nginx
  - docker build -t express-server ./server
  - docker build -t worker ./worker
