sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t react-client ./client
  - docker build -t nginx-router ./nginx
  - docker build -t express-server ./server
  - docker build -t worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to Docker Hub
  - docker push react-client
  - docker push nginx-router
  - docker push express-server
  - docker push worker
